.TH TRAITRELAX 1 LOCAL

.SH NAME

traitrelax - Detects association between changes in phenotype traits with changes in selection intensity at the codon level across a phylogeny

.SH SYNOPSIS

.B traitrelax [options]

.SH AVAILABILITY

All UNIX flavors

.SH DESCRIPTION

tritrelax  association of changes in phenotype traits with changes in selection intensity at the codon level across a phylogeny as described in https://www.biorxiv.org/content/10.1101/2020.03.04.974584v1.

.SH OPTIONS

You should refer to 'info traitrelax' or to the online manual of traitrelax for a complete list of available options.

.TP 5

--noninteractive

generates output for redirection in a file.

.TP

param=file

reads a file for loading options

.SH AUTHOR

Kren Halabi, Eli Levy Karin, Laurent Guéguen, and Itay Mayrose.